// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/rpkirtr.proto

package rpkirtripb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsRequest) Reset()         { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()    {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bc03bc5bc207f82, []int{0}
}

func (m *GetStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsRequest.Unmarshal(m, b)
}
func (m *GetStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsRequest.Merge(m, src)
}
func (m *GetStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatsRequest.Size(m)
}
func (m *GetStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsRequest proto.InternalMessageInfo

type GetStatsResponse struct {
	RoaCount             uint32            `protobuf:"varint,1,opt,name=roa_count,json=roaCount,proto3" json:"roa_count,omitempty"`
	ClientCount          uint32            `protobuf:"varint,2,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	Serial               uint32            `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	LastUpdate           int64             `protobuf:"varint,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Upstreams            []*UpstreamStatus `protobuf:"bytes,5,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStatsResponse) Reset()         { *m = GetStatsResponse{} }
func (m *GetStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatsResponse) ProtoMessage()    {}
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bc03bc5bc207f82, []int{1}
}

func (m *GetStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsResponse.Unmarshal(m, b)
}
func (m *GetStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsResponse.Merge(m, src)
}
func (m *GetStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatsResponse.Size(m)
}
func (m *GetStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsResponse proto.InternalMessageInfo

func (m *GetStatsResponse) GetRoaCount() uint32 {
	if m != nil {
		return m.RoaCount
	}
	return 0
}

func (m *GetStatsResponse) GetClientCount() uint32 {
	if m != nil {
		return m.ClientCount
	}
	return 0
}

func (m *GetStatsResponse) GetSerial() uint32 {
	if m != nil {
		return m.Serial
	}
	return 0
}

func (m *GetStatsResponse) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *GetStatsResponse) GetUpstreams() []*UpstreamStatus {
	if m != nil {
		return m.Upstreams
	}
	return nil
}

type UpstreamStatus struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	LastFetchSuccess     bool     `protobuf:"varint,2,opt,name=last_fetch_success,json=lastFetchSuccess,proto3" json:"last_fetch_success,omitempty"`
	LastFetchTime        int64    `protobuf:"varint,3,opt,name=last_fetch_time,json=lastFetchTime,proto3" json:"last_fetch_time,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpstreamStatus) Reset()         { *m = UpstreamStatus{} }
func (m *UpstreamStatus) String() string { return proto.CompactTextString(m) }
func (*UpstreamStatus) ProtoMessage()    {}
func (*UpstreamStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bc03bc5bc207f82, []int{2}
}

func (m *UpstreamStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamStatus.Unmarshal(m, b)
}
func (m *UpstreamStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamStatus.Marshal(b, m, deterministic)
}
func (m *UpstreamStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamStatus.Merge(m, src)
}
func (m *UpstreamStatus) XXX_Size() int {
	return xxx_messageInfo_UpstreamStatus.Size(m)
}
func (m *UpstreamStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamStatus proto.InternalMessageInfo

func (m *UpstreamStatus) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UpstreamStatus) GetLastFetchSuccess() bool {
	if m != nil {
		return m.LastFetchSuccess
	}
	return false
}

func (m *UpstreamStatus) GetLastFetchTime() int64 {
	if m != nil {
		return m.LastFetchTime
	}
	return 0
}

func (m *UpstreamStatus) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*GetStatsRequest)(nil), "rpkirtr.v1.GetStatsRequest")
	proto.RegisterType((*GetStatsResponse)(nil), "rpkirtr.v1.GetStatsResponse")
	proto.RegisterType((*UpstreamStatus)(nil), "rpkirtr.v1.UpstreamStatus")
}

func init() {
	proto.RegisterFile("api/v1/rpkirtr.proto", fileDescriptor_4bc03bc5bc207f82)
}

var fileDescriptor_4bc03bc5bc207f82 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x4b, 0xe3, 0x40,
	0x14, 0xc5, 0xc9, 0x66, 0xb7, 0x34, 0xb7, 0x7f, 0x77, 0x58, 0x96, 0xd0, 0x2e, 0x6c, 0xb7, 0x0b,
	0x4b, 0x1f, 0x96, 0x84, 0xb6, 0x08, 0x82, 0x6f, 0x8a, 0x8a, 0x88, 0x20, 0xd3, 0x16, 0xc1, 0x97,
	0x30, 0x4d, 0x6f, 0xdb, 0xc1, 0xa4, 0x13, 0xe7, 0x4f, 0xfd, 0x34, 0x7e, 0x1c, 0xbf, 0x97, 0x64,
	0x92, 0xda, 0x2a, 0xbe, 0xe5, 0x9c, 0xdf, 0x81, 0xdc, 0x33, 0xf7, 0xc2, 0x0f, 0x96, 0xf1, 0x70,
	0x3b, 0x0c, 0x65, 0xf6, 0xc0, 0xa5, 0x96, 0x41, 0x26, 0x85, 0x16, 0x04, 0x76, 0x72, 0x3b, 0xec,
	0x7f, 0x87, 0xd6, 0x25, 0xea, 0x89, 0x66, 0x5a, 0x51, 0x7c, 0x34, 0xa8, 0x74, 0xff, 0xc5, 0x81,
	0xf6, 0xde, 0x53, 0x99, 0xd8, 0x28, 0x24, 0x5d, 0xf0, 0xa4, 0x60, 0x51, 0x2c, 0xcc, 0x46, 0xfb,
	0x4e, 0xcf, 0x19, 0x34, 0x68, 0x55, 0x0a, 0x76, 0x96, 0x6b, 0xf2, 0x07, 0xea, 0x71, 0xc2, 0x71,
	0xa3, 0x4b, 0xfe, 0xc5, 0xf2, 0x5a, 0xe1, 0x15, 0x91, 0x9f, 0x50, 0x51, 0x28, 0x39, 0x4b, 0x7c,
	0xd7, 0xc2, 0x52, 0x91, 0xdf, 0x50, 0x4b, 0x98, 0xd2, 0x91, 0xc9, 0x16, 0x4c, 0xa3, 0xff, 0xb5,
	0xe7, 0x0c, 0x5c, 0x0a, 0xb9, 0x35, 0xb3, 0x0e, 0x39, 0x06, 0xcf, 0x64, 0x4a, 0x4b, 0x64, 0xa9,
	0xf2, 0xbf, 0xf5, 0xdc, 0x41, 0x6d, 0xd4, 0x09, 0xf6, 0x05, 0x82, 0x59, 0x09, 0xf3, 0x71, 0x8d,
	0xa2, 0xfb, 0x70, 0xff, 0xd9, 0x81, 0xe6, 0x7b, 0x4a, 0xda, 0xe0, 0x1a, 0x99, 0xd8, 0xf9, 0x3d,
	0x9a, 0x7f, 0x92, 0xff, 0x40, 0xec, 0xff, 0x97, 0xa8, 0xe3, 0x75, 0xa4, 0x4c, 0x1c, 0xa3, 0x52,
	0xb6, 0x40, 0x95, 0xb6, 0x73, 0x72, 0x91, 0x83, 0x49, 0xe1, 0x93, 0x7f, 0xd0, 0x3a, 0x48, 0x6b,
	0x9e, 0xa2, 0xad, 0xe3, 0xd2, 0xc6, 0x5b, 0x74, 0xca, 0x53, 0x24, 0x7f, 0xa1, 0x81, 0x52, 0x0a,
	0x19, 0xa5, 0xa8, 0x14, 0x5b, 0x15, 0xbd, 0x3c, 0x5a, 0xb7, 0xe6, 0x4d, 0xe1, 0x8d, 0xee, 0xa0,
	0x49, 0x6f, 0xaf, 0xaf, 0xe8, 0x94, 0x4e, 0x50, 0x6e, 0x79, 0x8c, 0xe4, 0x1c, 0xaa, 0xbb, 0x87,
	0x27, 0xdd, 0xc3, 0x92, 0x1f, 0x56, 0xd4, 0xf9, 0xf5, 0x39, 0x2c, 0x76, 0x75, 0x7a, 0x74, 0x3f,
	0x5e, 0x71, 0xbd, 0x36, 0xf3, 0x20, 0x16, 0x69, 0x98, 0x62, 0x92, 0x88, 0xa7, 0x85, 0xe4, 0x4b,
	0x8d, 0x72, 0x77, 0x09, 0xa3, 0xb0, 0xb8, 0x8c, 0x93, 0x52, 0xf3, 0x6c, 0x3e, 0xaf, 0xd8, 0xeb,
	0x18, 0xbf, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xc3, 0xfe, 0x31, 0x35, 0x02, 0x00, 0x00,
}
