// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/v1/rpkirtr.proto

package rpkirtripb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPKIRTRService_GetStats_FullMethodName = "/rpkirtr.v1.RPKIRTRService/GetStats"
)

// RPKIRTRServiceClient is the client API for RPKIRTRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPKIRTRServiceClient interface {
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type rPKIRTRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPKIRTRServiceClient(cc grpc.ClientConnInterface) RPKIRTRServiceClient {
	return &rPKIRTRServiceClient{cc}
}

func (c *rPKIRTRServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, RPKIRTRService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPKIRTRServiceServer is the server API for RPKIRTRService service.
// All implementations must embed UnimplementedRPKIRTRServiceServer
// for forward compatibility.
type RPKIRTRServiceServer interface {
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedRPKIRTRServiceServer()
}

// UnimplementedRPKIRTRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPKIRTRServiceServer struct{}

func (UnimplementedRPKIRTRServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedRPKIRTRServiceServer) mustEmbedUnimplementedRPKIRTRServiceServer() {}
func (UnimplementedRPKIRTRServiceServer) testEmbeddedByValue()                        {}

// UnsafeRPKIRTRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPKIRTRServiceServer will
// result in compilation errors.
type UnsafeRPKIRTRServiceServer interface {
	mustEmbedUnimplementedRPKIRTRServiceServer()
}

func RegisterRPKIRTRServiceServer(s grpc.ServiceRegistrar, srv RPKIRTRServiceServer) {
	// If the following call panics, it indicates UnimplementedRPKIRTRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPKIRTRService_ServiceDesc, srv)
}

func _RPKIRTRService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPKIRTRServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPKIRTRService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPKIRTRServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPKIRTRService_ServiceDesc is the grpc.ServiceDesc for RPKIRTRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPKIRTRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpkirtr.v1.RPKIRTRService",
	HandlerType: (*RPKIRTRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _RPKIRTRService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/rpkirtr.proto",
}
